ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_country VARCHAR(120);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_phone VARCHAR(50);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(80);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS promo_code VARCHAR(80);
